//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Business.DTOs")]
    public partial class PlayerDto : PlayerReference.BaseDto
    {
        
        private System.DateTime DateBirthField;
        
        private string FirstNameField;
        
        private float HeightField;
        
        private string LastNameField;
        
        private decimal MarketValueField;
        
        private string PositionField;
       
        private PlayerReference.TeamDto TeamField;
        
        private int TeamIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBirth
        {
            get
            {
                return this.DateBirthField;
            }
            set
            {
                this.DateBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketValue
        {
            get
            {
                return this.MarketValueField;
            }
            set
            {
                this.MarketValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlayerReference.TeamDto Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId
        {
            get
            {
                return this.TeamIdField;
            }
            set
            {
                this.TeamIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDto", Namespace="http://schemas.datacontract.org/2004/07/Business.DTOs")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PlayerReference.TeamDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PlayerReference.PlayerDto))]
    public partial class BaseDto : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamDto", Namespace="http://schemas.datacontract.org/2004/07/Business")]
    public partial class TeamDto : PlayerReference.BaseDto
    {
        
        private double AverageAgePlayersField;
        
        private string CountryField;
        
        private System.DateTime DateCreationField;
        
        private decimal NetWorthField;
        
        private string TeamNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AverageAgePlayers
        {
            get
            {
                return this.AverageAgePlayersField;
            }
            set
            {
                this.AverageAgePlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation
        {
            get
            {
                return this.DateCreationField;
            }
            set
            {
                this.DateCreationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWorth
        {
            get
            {
                return this.NetWorthField;
            }
            set
            {
                this.NetWorthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName
        {
            get
            {
                return this.TeamNameField;
            }
            set
            {
                this.TeamNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerReference.IPlayers")]
    public interface IPlayers
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/GetAllByTeam", ReplyAction="http://tempuri.org/IPlayers/GetAllByTeamResponse")]
        PlayerReference.PlayerDto[] GetAllByTeam(string teamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/GetAllByTeam", ReplyAction="http://tempuri.org/IPlayers/GetAllByTeamResponse")]
        System.Threading.Tasks.Task<PlayerReference.PlayerDto[]> GetAllByTeamAsync(string teamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/GetAll", ReplyAction="http://tempuri.org/IPlayers/GetAllResponse")]
        PlayerReference.PlayerDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/GetAll", ReplyAction="http://tempuri.org/IPlayers/GetAllResponse")]
        System.Threading.Tasks.Task<PlayerReference.PlayerDto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/GetById", ReplyAction="http://tempuri.org/IPlayers/GetByIdResponse")]
        PlayerReference.PlayerDto GetById(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/GetById", ReplyAction="http://tempuri.org/IPlayers/GetByIdResponse")]
        System.Threading.Tasks.Task<PlayerReference.PlayerDto> GetByIdAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/Create", ReplyAction="http://tempuri.org/IPlayers/CreateResponse")]
        string Create(PlayerReference.PlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/Create", ReplyAction="http://tempuri.org/IPlayers/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(PlayerReference.PlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/Update", ReplyAction="http://tempuri.org/IPlayers/UpdateResponse")]
        string Update(PlayerReference.PlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/Update", ReplyAction="http://tempuri.org/IPlayers/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(PlayerReference.PlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/Delete", ReplyAction="http://tempuri.org/IPlayers/DeleteResponse")]
        string Delete(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayers/Delete", ReplyAction="http://tempuri.org/IPlayers/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPlayersChannel : PlayerReference.IPlayers, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PlayersClient : System.ServiceModel.ClientBase<PlayerReference.IPlayers>, PlayerReference.IPlayers
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PlayersClient() : 
                base(PlayersClient.GetDefaultBinding(), PlayersClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PlayersService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayersClient(EndpointConfiguration endpointConfiguration) : 
                base(PlayersClient.GetBindingForEndpoint(endpointConfiguration), PlayersClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayersClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PlayersClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayersClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PlayersClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlayersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PlayerReference.PlayerDto[] GetAllByTeam(string teamName)
        {
            return base.Channel.GetAllByTeam(teamName);
        }
        
        public System.Threading.Tasks.Task<PlayerReference.PlayerDto[]> GetAllByTeamAsync(string teamName)
        {
            return base.Channel.GetAllByTeamAsync(teamName);
        }
        
        public PlayerReference.PlayerDto[] GetAll()
        {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PlayerReference.PlayerDto[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public PlayerReference.PlayerDto GetById(int playerId)
        {
            return base.Channel.GetById(playerId);
        }
        
        public System.Threading.Tasks.Task<PlayerReference.PlayerDto> GetByIdAsync(int playerId)
        {
            return base.Channel.GetByIdAsync(playerId);
        }
        
        public string Create(PlayerReference.PlayerDto player)
        {
            return base.Channel.Create(player);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(PlayerReference.PlayerDto player)
        {
            return base.Channel.CreateAsync(player);
        }
        
        public string Update(PlayerReference.PlayerDto player)
        {
            return base.Channel.Update(player);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(PlayerReference.PlayerDto player)
        {
            return base.Channel.UpdateAsync(player);
        }
        
        public string Delete(int playerId)
        {
            return base.Channel.Delete(playerId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int playerId)
        {
            return base.Channel.DeleteAsync(playerId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PlayersService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PlayersService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53506/Players.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PlayersClient.GetBindingForEndpoint(EndpointConfiguration.PlayersService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PlayersClient.GetEndpointAddress(EndpointConfiguration.PlayersService);
        }
        
        public enum EndpointConfiguration
        {
            
            PlayersService,
        }
    }
}
