//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamDto", Namespace="http://schemas.datacontract.org/2004/07/Business")]
    public partial class TeamDto : ServiceReference1.BaseDto
    {
        
        private double AverageAgePlayersField;
        
        private string CountryField;
        
        private System.DateTime DateCreationField;
        
        private decimal NetWorthField;
        
        private string TeamNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AverageAgePlayers
        {
            get
            {
                return this.AverageAgePlayersField;
            }
            set
            {
                this.AverageAgePlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation
        {
            get
            {
                return this.DateCreationField;
            }
            set
            {
                this.DateCreationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWorth
        {
            get
            {
                return this.NetWorthField;
            }
            set
            {
                this.NetWorthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName
        {
            get
            {
                return this.TeamNameField;
            }
            set
            {
                this.TeamNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDto", Namespace="http://schemas.datacontract.org/2004/07/Business.DTOs")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TeamDto))]
    public partial class BaseDto : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITeams")]
    public interface ITeams
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/GetAllByName", ReplyAction="http://tempuri.org/ITeams/GetAllByNameResponse")]
        ServiceReference1.TeamDto[] GetAllByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/GetAllByName", ReplyAction="http://tempuri.org/ITeams/GetAllByNameResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TeamDto[]> GetAllByNameAsync(string name);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITeams/GetAllByCountry", ReplyAction = "http://tempuri.org/ITeams/GetAllByCountryResponse")]
        ServiceReference1.TeamDto[] GetAllByCountry(string name);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITeams/GetAllByCountry", ReplyAction = "http://tempuri.org/ITeams/GetAllByCountryResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TeamDto[]> GetAllByCountryAsync(string name);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/GetAll", ReplyAction="http://tempuri.org/ITeams/GetAllResponse")]
        ServiceReference1.TeamDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/GetAll", ReplyAction="http://tempuri.org/ITeams/GetAllResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TeamDto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/GetById", ReplyAction="http://tempuri.org/ITeams/GetByIdResponse")]
        ServiceReference1.TeamDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/GetById", ReplyAction="http://tempuri.org/ITeams/GetByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TeamDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/Create", ReplyAction="http://tempuri.org/ITeams/CreateResponse")]
        string Create(ServiceReference1.TeamDto team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/Create", ReplyAction="http://tempuri.org/ITeams/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(ServiceReference1.TeamDto team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/Update", ReplyAction="http://tempuri.org/ITeams/UpdateResponse")]
        string Update(ServiceReference1.TeamDto team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/Update", ReplyAction="http://tempuri.org/ITeams/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(ServiceReference1.TeamDto team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/Delete", ReplyAction="http://tempuri.org/ITeams/DeleteResponse")]
        string Delete(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeams/Delete", ReplyAction="http://tempuri.org/ITeams/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int teamId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ITeamsChannel : ServiceReference1.ITeams, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TeamsClient : System.ServiceModel.ClientBase<ServiceReference1.ITeams>, ServiceReference1.ITeams
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TeamsClient() : 
                base(TeamsClient.GetDefaultBinding(), TeamsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITeams.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeamsClient(EndpointConfiguration endpointConfiguration) : 
                base(TeamsClient.GetBindingForEndpoint(endpointConfiguration), TeamsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeamsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TeamsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeamsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TeamsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeamsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.TeamDto[] GetAllByName(string name)
        {
            return base.Channel.GetAllByName(name);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TeamDto[]> GetAllByNameAsync(string name)
        {
            return base.Channel.GetAllByNameAsync(name);
        }

        public ServiceReference1.TeamDto[] GetAllByCountry(string country)
        {
            return base.Channel.GetAllByName(country);
        }

        public System.Threading.Tasks.Task<ServiceReference1.TeamDto[]> GetAllByCountryAsync(string country)
        {
            return base.Channel.GetAllByNameAsync(country);
        }

        public ServiceReference1.TeamDto[] GetAll()
        {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TeamDto[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public ServiceReference1.TeamDto GetById(int id)
        {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TeamDto> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public string Create(ServiceReference1.TeamDto team)
        {
            return base.Channel.Create(team);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(ServiceReference1.TeamDto team)
        {
            return base.Channel.CreateAsync(team);
        }
        
        public string Update(ServiceReference1.TeamDto team)
        {
            return base.Channel.Update(team);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(ServiceReference1.TeamDto team)
        {
            return base.Channel.UpdateAsync(team);
        }
        
        public string Delete(int teamId)
        {
            return base.Channel.Delete(teamId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int teamId)
        {
            return base.Channel.DeleteAsync(teamId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITeams))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITeams))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53506/Teams.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TeamsClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITeams);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TeamsClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITeams);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITeams,
        }
    }
}
