//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferDto", Namespace="http://schemas.datacontract.org/2004/07/Business.DTOs")]
    public partial class TransferDto : TransfersReference.BaseDto
    {
        
        private System.DateTime DateTransferField;
        
        private decimal MoneyAmountField;
        
        private TransfersReference.PlayerDto PlayerField;
        
        private TransfersReference.TeamDto TeamJoinedField;
        
        private TransfersReference.TeamDto TeamLeftField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTransfer
        {
            get
            {
                return this.DateTransferField;
            }
            set
            {
                this.DateTransferField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyAmount
        {
            get
            {
                return this.MoneyAmountField;
            }
            set
            {
                this.MoneyAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransfersReference.PlayerDto Player
        {
            get
            {
                return this.PlayerField;
            }
            set
            {
                this.PlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransfersReference.TeamDto TeamJoined
        {
            get
            {
                return this.TeamJoinedField;
            }
            set
            {
                this.TeamJoinedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransfersReference.TeamDto TeamLeft
        {
            get
            {
                return this.TeamLeftField;
            }
            set
            {
                this.TeamLeftField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDto", Namespace="http://schemas.datacontract.org/2004/07/Business.DTOs")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TransfersReference.PlayerDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TransfersReference.TeamDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TransfersReference.TransferDto))]
    public partial class BaseDto : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDto", Namespace="http://schemas.datacontract.org/2004/07/Business.DTOs")]
    public partial class PlayerDto : TransfersReference.BaseDto
    {
        
        private System.DateTime DateBirthField;
        
        private string FirstNameField;
        
        private float HeightField;
        
        private string LastNameField;
        
        private decimal MarketValueField;
        
        private string PositionField;
        
        private TransfersReference.TeamDto TeamField;
        
        private int TeamIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBirth
        {
            get
            {
                return this.DateBirthField;
            }
            set
            {
                this.DateBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketValue
        {
            get
            {
                return this.MarketValueField;
            }
            set
            {
                this.MarketValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransfersReference.TeamDto Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId
        {
            get
            {
                return this.TeamIdField;
            }
            set
            {
                this.TeamIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamDto", Namespace="http://schemas.datacontract.org/2004/07/Business")]
    public partial class TeamDto : TransfersReference.BaseDto
    {
        
        private double AverageAgePlayersField;
        
        private string CountryField;
        
        private System.DateTime DateCreationField;
        
        private decimal NetWorthField;
        
        private string TeamNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AverageAgePlayers
        {
            get
            {
                return this.AverageAgePlayersField;
            }
            set
            {
                this.AverageAgePlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation
        {
            get
            {
                return this.DateCreationField;
            }
            set
            {
                this.DateCreationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWorth
        {
            get
            {
                return this.NetWorthField;
            }
            set
            {
                this.NetWorthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName
        {
            get
            {
                return this.TeamNameField;
            }
            set
            {
                this.TeamNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransfersReference.ITransfers")]
    public interface ITransfers
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/GetAll", ReplyAction="http://tempuri.org/ITransfers/GetAllResponse")]
        TransfersReference.TransferDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/GetAll", ReplyAction="http://tempuri.org/ITransfers/GetAllResponse")]
        System.Threading.Tasks.Task<TransfersReference.TransferDto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/GetById", ReplyAction="http://tempuri.org/ITransfers/GetByIdResponse")]
        TransfersReference.TransferDto GetById(int transferId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/GetById", ReplyAction="http://tempuri.org/ITransfers/GetByIdResponse")]
        System.Threading.Tasks.Task<TransfersReference.TransferDto> GetByIdAsync(int transferId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/Create", ReplyAction="http://tempuri.org/ITransfers/CreateResponse")]
        string Create(TransfersReference.TransferDto transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/Create", ReplyAction="http://tempuri.org/ITransfers/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(TransfersReference.TransferDto transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/Update", ReplyAction="http://tempuri.org/ITransfers/UpdateResponse")]
        string Update(TransfersReference.TransferDto transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/Update", ReplyAction="http://tempuri.org/ITransfers/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(TransfersReference.TransferDto transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/Delete", ReplyAction="http://tempuri.org/ITransfers/DeleteResponse")]
        string Delete(int transferId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransfers/Delete", ReplyAction="http://tempuri.org/ITransfers/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int transferId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ITransfersChannel : TransfersReference.ITransfers, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TransfersClient : System.ServiceModel.ClientBase<TransfersReference.ITransfers>, TransfersReference.ITransfers
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransfersClient() : 
                base(TransfersClient.GetDefaultBinding(), TransfersClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITransfers.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransfersClient(EndpointConfiguration endpointConfiguration) : 
                base(TransfersClient.GetBindingForEndpoint(endpointConfiguration), TransfersClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransfersClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransfersClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransfersClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransfersClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransfersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TransfersReference.TransferDto[] GetAll()
        {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TransfersReference.TransferDto[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public TransfersReference.TransferDto GetById(int transferId)
        {
            return base.Channel.GetById(transferId);
        }
        
        public System.Threading.Tasks.Task<TransfersReference.TransferDto> GetByIdAsync(int transferId)
        {
            return base.Channel.GetByIdAsync(transferId);
        }
        
        public string Create(TransfersReference.TransferDto transfer)
        {
            return base.Channel.Create(transfer);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(TransfersReference.TransferDto transfer)
        {
            return base.Channel.CreateAsync(transfer);
        }
        
        public string Update(TransfersReference.TransferDto transfer)
        {
            return base.Channel.Update(transfer);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(TransfersReference.TransferDto transfer)
        {
            return base.Channel.UpdateAsync(transfer);
        }
        
        public string Delete(int transferId)
        {
            return base.Channel.Delete(transferId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int transferId)
        {
            return base.Channel.DeleteAsync(transferId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransfers))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransfers))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53506/Transfers.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TransfersClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITransfers);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TransfersClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITransfers);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITransfers,
        }
    }
}
